version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: matplotlib
    versions:
    - 3.3.4
    - 3.4.0
  - dependency-name: scipy
    versions:
    - 1.6.0
    - 1.6.1
    - 1.6.2
  - dependency-name: h5py
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
  - dependency-name: tensorboard
    versions:
    - 2.4.1
  - dependency-name: absl-py
    versions:
    - 0.11.0
  - dependency-name: bleach
    versions:
    - 3.1.1
  - dependency-name: pyyaml
    versions:
    - "5.1"
